<?php

//Datos BBDD
define('DB_HOST', 'localhost'); //NOMBRE DEL HOST, EN ESTE CASO SERVIDOR LOCAL
define('DB_USER', 'root'); //NOMBRE DEL USER DE LA DDBB
define('DB_PASSWORD', 'root'); //CONTRASEÑA DE LA DDBB
define('DB_NAME', 'todomochilas'); //NOMBRE DE LA DDBB

define('DEBUG_MODE', true); //CONFIGURACION DE DEPURACION

define('DIR_MOCHILA', '../img/mochilas/'); //RUTA RAIZ PARA GUARDAR LAS FOTOS DE LAS MOCHILAS EN EL FORMULARIO DE REGISTRO DE PRODUCTO

